### ISSUE TITLE
Revision control metadata errors

### ISSUE THREAD

**Issue by pschuegr** [Unitech/PM2#1009]
This seems to work on first run, but using pm2 info eventually errors on the revision control info.

```
Revision control metadata

/Users/pschuegr/ss/server/node_modules/pm2/node_modules/cli-table/lib/index.js:182
      var contents = item.toString().split("\n").reduce(function (memo, l) {
                          ^
TypeError: Cannot call method 'toString' of undefined
```

pm2 version 0.12.5
node version 0.10.35

**Comment by pschuegr** [comment]
Sorry, here's the rest of the callstack;

```
TypeError: Cannot call method 'toString' of undefined
    at /Users/pschuegr/weltel/server/node_modules/pm2/node_modules/cli-table/lib/index.js:182:27
    at Array.forEach (native)
    at generateRow (/Users/pschuegr/weltel/server/node_modules/pm2/node_modules/cli-table/lib/index.js:181:11)
    at /Users/pschuegr/weltel/server/node_modules/pm2/node_modules/cli-table/lib/index.js:275:16
    at Table.forEach (native)
    at Table.toString (/Users/pschuegr/weltel/server/node_modules/pm2/node_modules/cli-table/lib/index.js:258:10)
    at Object.UX.describeTable (/Users/pschuegr/weltel/server/node_modules/pm2/lib/CliUx.js:96:24)
    at /Users/pschuegr/weltel/server/node_modules/pm2/lib/CLI.js:1146:12
    at Array.forEach (native)
    at /Users/pschuegr/weltel/server/node_modules/pm2/lib/CLI.js:1145:18
```

Looks like it might be a cli-table issue?

**Comment by pschuegr** [comment]
It's because the repo_path eventually comes back as undefined, which explodes cli-table.  Don't have time to dig further atm.

**Comment by jshkurti** [comment]
Fixed, thanks for the feedback :)
https://github.com/Unitech/PM2/commit/1627209ce511ce64b0c313dbadc620d8aed171da

**Comment by raine** [comment]
I have the change from 1627209 but still get the error:

```
Revision control metadata
/usr/local/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:182
      var contents = item.toString().split("\n").reduce(function (memo, l) {
                         ^
TypeError: Cannot read property 'toString' of undefined
    at /usr/local/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:182:26
```

**Comment by jshkurti** [comment]
Try ```pm2 update```

**Comment by raine** [comment]
Thanks. That fixed it. I guess there was actually an old version of pm2 running in the background.

**Comment by starsirius** [comment]
@jshkurti I am still getting the same error after all the steps above. If I go back and use 0.9.6, it works fine. Any advice? Thanks.

pm2 0.12.8
node v0.12.0
os Ubuntu 14.04

**Comment by jshkurti** [comment]
```pm2 kill; pkill -f PM2; pkill -9 PM2; npm i -g pm2@latest```
If it happens again, show me some ```~/.pm2/pm2.logs``` please :)

**Comment by starsirius** [comment]
yeah still no luck. :(

Here is the `~/.pm2/pm2.logs`
```
2015-03-22 20:43:18: [PM2][WORKER] Started with refreshing interval: 30000
2015-03-22 20:43:18: [[[[ PM2/God daemon launched ]]]]
2015-03-22 20:43:18: BUS system [READY] on port /home/takoman/.pm2/pub.sock
2015-03-22 20:43:18: RPC interface [READY] on port /home/takoman/.pm2/rpc.sock
2015-03-22 20:43:18: Starting execution sequence in -fork mode- for app name:index id:0
2015-03-22 20:43:18: App name:index id:0 online
2015-03-22 20:43:18: Error: spawn coffee ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickDomainCallback (node.js:381:11)
```
