### ISSUE TITLE
God Daemon taking up huge amounts of memory

### ISSUE THREAD

**Issue by mattstrayer** [Unitech/PM2#1126]
The app itself runs at about 60-70mb of memory. Running on a small Digital Ocean Droplet (14.04 Ubuntu), but the god Daemon takes up the rest of the 512mb of memory and clogs the system. Node is running v0.12.

**Comment by danieljuhl** [comment]
I'm starting to see the same behavior.

PM2 Deamon & PM2 Keymetrics is slowly increasing their memory footprint over time. Running PM2 v0.12.10 with node v0.12.2 on a Digital Ocean Droplet (Ubuntu 14.04).

**Comment by jorge-d** [comment]
Did you integrate [pmx](https://github.com/keymetrics/pmx) as well in your application ? Just trying to figure out whether the issue might come from the **pm2** or **pmx** :)

**Comment by danieljuhl** [comment]
@jorge-d No, I haven't used pmx - only pm2 with keymetrics.

**Comment by Unitech** [comment]
@danieljuhl @mattstrayer how many applications do you use? In which mode (cluster/fork)? Do you processes constantly restart?

If you still have the pm2 logs (~/.pm2/pm2.log) would appreciate to know if something strange happened.

We are using it at Keymetrics to manage processes on 6 different servers (Ubuntu 14.04, Node 0.12.2) running 10 applications (4 in cluster mode and 6 in fork mode) and we don't see this behavior.

**Comment by danieljuhl** [comment]
I've seen the issue on an instance which runs two apps: the built-in http service and one other application in simple fork mode ("pm2 start app.js"). That application is a heavy backend app, but does not restart during the test period, where memory is increased for pm2. I use the max memory restart option, but during the test period, that treshold has not been reached.

I'll have a look at the pm2 logs.

**Comment by hefangshi** [comment]
I got some issues with pmx too, my application got memory leak when using pm2 0.12, so I checked with heapdump, found that a object using domain was the leak source, and seems related with pmx, so I disabled pmx init in processContainer.js and everything goes fine.

I didn't work out a min demo for this case due to time reason, but just give a hint.

**Comment by angrycoding** [comment]
Hi, I also have same issue; CentOS6 32, pm2@0.12.11, node@0.12.2, I'm running one application in fork mode, and according to pm2 monit it eats just 64MB, but htop shows that there are 5 child "God Daemon" processes, as well as 5 copies of my apps running, which is in overall takes about 40% of all memory.

**Comment by Unitech** [comment]
It's been fixed with the 0.12.11, we now force the GC, now PM2 always stay at around 50mb (4 benchmarks on 4 machines with bad application behaviors)

@angrycoding #1088

**Comment by angrycoding** [comment]
Yeah I'm sorry, spend all day on investigating this thing, came out that this was unix caches that was growing... after clearing caches everything runs smoothly, thanks for the great product!

**Comment by imgovind** [comment]
Thank you Alexandre.

**Comment by hefangshi** [comment]
:-1: force gc is not a good idea, and need user to expose gc which might be abused.

I strongly recommand that we should look into pmx https://github.com/Unitech/PM2/issues/1126#issuecomment-93775713 rather than trigger gc manually.

**Comment by andersonmadeira** [comment]
I'm using version 12.12 and I still have this issue. Used memory gets bigger each minute.

**Comment by mpechner** [comment]
Using 0.15.10 and it also blows up.
Nodejs version 4.2.2

One app is all it runs:  pm2 start /opt/node/latest/app.js

**Comment by neekfenwick** [comment]
FYI I'm troubleshooting this here, I think in my case the issue is that pm2 is being run as root and ubuntu users alternately.  I'm using Amazon CodeDeploy, where the lifecycle scripts ApplicationStart and ValidateService are 'accidentally' being run as `ubuntu` and `root` users respectively.  ApplicationStart starts the app with `pm2 start --name foo blah blah blah`, then ValidateService runs `pm2 info foo` in an attempt to list its info with an exit status of zero, and thus indicate to CodeDeploy that it's running OK.  After this, I see this in `top`:

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                        
16324 root      20   0 3542056 2.575g   8560 R 100.2 33.0   7:43.29 PM2 v1.1.3: God                                                                                
16306 ubuntu    20   0 1043140  43784   9188 S   0.0  0.5   0:00.76 node /home/ubun                                                                                
 8403 root      20   0  323236  35876   3408 S   0.0  0.4   0:02.53 codedeploy-agen                                                                                
13923 ubuntu    20   0  945328  25356   3976 S   0.0  0.3   0:02.42 PM2 v1.1.3: God                                                                                
 8399 root      20   0   93624  16604      0 S   0.0  0.2   0:00.38 codedeploy-agen      
```
So there are two God processes, the one owned by `root` has gone to 100% CPU and its memory footprint just keeps on growing (while typing this it went from 2.5Gb to 2.9Gb).

**Comment by Dublerq** [comment]
Same issue here on Ubuntu 14.04, PM2 1.1.3 and node 4.4.7

**Comment by Dublerq** [comment]
I was using latest pm2 downloaded a few days ago. Somehow I've managed to fix it just by clearing all the cache, dumps, logs, startups and logs. Can't reproduce the problem anymore

**Comment by Pranav-Saxena** [comment]
hey this issue is occuring again on PM2 v5.0.4. what to do? it takes around 400 mb of ram

**Comment by victor-ono** [comment]
I'm started experiencing this issue as well after updating. It takes 50% of RAM on a 512MB machine!
<img width="611" alt="Screen Shot 2021-08-06 at 1 10 24 PM" src="https://user-images.githubusercontent.com/519311/128547663-d808292a-2085-4e5b-9402-2465b9bdefb4.png">

**Comment by yi** [comment]
I just experienced this issue and found the root cause is [NodeJS backpressure](https://nodejs.org/en/docs/guides/backpressuring-in-streams/). Basically, pm2 failed to flush the log to disk in time (too much log output). And this issue was solved by reducing log output.

**Comment by shizheng163** [comment]
vizion cause memory used, you can see the issue: https://github.com/Unitech/pm2/issues/5051

you can use `–no-vizion` start your app to avoid the problem.
