### ISSUE TITLE
'pm2 plus' command not recognized, otherwise pm2 runs just fine - need to link to keymetrics.io

### ISSUE THREAD

**Issue by tamaker** [Unitech/pm2#3887]
I have pm2 v3.0.4 installed on linux (ubuntu 16.04) and have had great success using pm2 API to manage Control my forked node.js processes for an enterprise app for our internal users.

The issue I'm having now that I want to make full use of keymetrics.io (web based analytics and process management SaaS) is that the command pm2 plus seems to not be recognized as a valid command, even after updating to latest pm2 build and confirming that the version number MATCHES the test version i have running on my macbook pro.

some permssions related issues require I run anything PM2 related with sudo -- for now, but I plan on resolving that later... so i'm not sure if that has anything to do with this issue... 

when I enter the command sudo pm2 plus XXXXXXXXX  YYYYYYYYY

all I get back is 'command not found' and the normal 'help' screen with commands and how to's for using PM2

running on ubuntu 16.04 server on an internal network.  Again, pm2 runs fine and I"m able to use the API for my own 'dashboard' of realtime data for processes and have triggers to manage / control the respective forked processes... the application performs beautifully... keymetrics.io (if its compatible with Linux) would just be even more impressive and useful to us with the app going into production soon.

Any ideas what I need to do here?  Thx.

**Comment by vmarchaud** [comment]
cc @Unitech

**Comment by tamaker** [comment]
update:  I just (grasping at straws) ran pm2 link instead of pm2 plus (remembering that in previous builds the command was 'link'... and it showed 'connecting...' and SEEMS to have worked....   But when I try to launch the bucket via web browser I just seek "loading subsystems"... I reached out yesterday and got a reply this am that this was due to a DNS issue in my area and it should now be fixed, but even after flushing DNS on my machine its not working.    I'll try making sure outbound ports are open now.

**Comment by tamaker** [comment]
no dice, still a problem for me, too bad ... was hoping to have access to keymetrics dashboard

**Comment by pranayhere** [comment]
I'm facing same problem

**Comment by Unitech** [comment]
Please update PM2

Or instead of `pm2 plus` use the legacy command  `pm2 link`

**Comment by aamakerlsa** [comment]
@Unitech - will retry both of these already (as noted in a previous post).   Hesitate to update and find another issue, I can live with out keymetrics.io integration and have written my own 'dashboard' basically as a fallback option... need this (my pm2 implementation) to remain solid as it is now for production in just a couple of days.

@pranayhere - No, still an issue but I've devised a plan to live without it.  Please let me know if you find any resolution with it.  What OS (and version) are you running it on, just curious?
